name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-nix:
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Cache Nix DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/nix
          key: ${{ runner.os }}-nixcache-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nixcache-

      - name: Build with Nix
        run: nix build
